config/routes.rb
Rails.application.routes.draw do
  resources :warehouse_changes
  resources :sale_products

  resources :sales
  post 'sale_disable/:id', to: "sales#disable", as: 'sale_disable'
  get 'start_new_sale', to: "sales#start_new_sale"

  resources :reasons
  root 'welcome#index'
  resources :products

  get 'reports', to: 'reports#index'
  get 'reports_sales', to: 'reports#sales'
  get 'reports_products', to: 'reports#products'
  get 'reports_warehouse_changes', to: 'reports#warehouse_changes'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/warehouse_change.rb
class WarehouseChange < ApplicationRecord
  belongs_to :product
  belongs_to :reason

  validates :product_id, presence: true, allow_blank: false
  validates :reason_id, presence: true, allow_blank: false
  validates :quantity, presence: true, allow_blank: false

  validate :cant_be_negative

  ADD_ID = Reason.all[0].id
  REMOVE_ID = Reason.all[1].id
  SELL_ID = Reason.all[2].id
  CANCELL_SELL_ID = Reason.all[3].id

  def self.total_itens(product_id)
    total = 0
    WarehouseChange.where(product_id: product_id).each do |wc|
      total += wc.get_change_real_value
    end

    return total
  end

  def get_change_real_value
    if self.reason.action.eql?('add')
      return self.quantity
    elsif self.reason.action.eql?('remove')
      return - self.quantity
    end
  end

  def cant_be_negative
    unless is_number?(self.quantity)
      errors.add(:quantity, "Deve ser número válido") 
      return ''
    end

    if self.quantity < 1
      errors.add(:quantity, "Deve ser maior que 0")
      return ''
    end

    total = WarehouseChange.total_itens(self.product_id)
    if (total + self.get_change_real_value) < 0
      errors.add(:quantity, "Estoque não pode ficar negativo. Existem #{total} itens em estoque")
    end
  end

  def self.product_quantity_is_available?(product_id, quantity)
    WarehouseChange.total_itens(product_id) >= quantity
  end

  def self.add_sell(product_id, quantity, sale_id)
    whc = WarehouseChange.create(
      product_id: product_id,
      reason_id: SELL_ID,
      quantity: quantity,
      description: "Sale ID: #{sale_id}"
    )
  end

  def self.return_itens_to_warehouse(sale_id)
    begin
      sale = Sale.find(sale_id)
      sale.sale_products.each do |sp|
        WarehouseChange.add_item_change(sp.product_id, CANCELL_SELL_ID, sp.quantity, "Venda cancelada, ID: #{sale_id}")
      end
    rescue
      return false
    end
    true
  end

  def self.warehouse_changes_by_date(start, finish)
    return WarehouseChange.where("created_at >= ? AND created_at <= ?", start.beginning_of_day, finish.end_of_day)
  end

  def self.warehouse_changes_by_date_and_product(start, finish, product_id)
    changes = WarehouseChange.warehouse_changes_by_date(start, finish)
    return changes.where(product_id: product_id)
  end

  def self.get_total_changed(warehouse_change_list)
    total = 0
    warehouse_change_list.each do |change|
      total = eval("#{total}" + "#{change.reason.get_math_symbol}" + "#{change.quantity}")
    end
    return total
  end

  def self.there_is_reason_associated?(reason_id)
    WarehouseChange.all.each do |wc|
      return true if wc.reason_id == reason_id
    end
    return false
  end

  private

    def self.add_item_change(product_id, reason_id, quantity, description)
      WarehouseChange.create!(product_id: product_id, reason_id: reason_id, quantity: quantity, description: description)
    end
end

app/controllers/warehouse_changes_controller.rb
class WarehouseChangesController < ApplicationController
  before_action :set_warehouse_change, only: [:show, :edit, :update, :destroy]

  # GET /warehouse_changes
  # GET /warehouse_changes.json
  def index
    @warehouse_changes = WarehouseChange.all
  end

  # GET /warehouse_changes/1
  # GET /warehouse_changes/1.json
  def show
  end

  # GET /warehouse_changes/new
  def new
    @warehouse_change = WarehouseChange.new
  end

  # GET /warehouse_changes/1/edit
  def edit
  end

  # POST /warehouse_changes
  # POST /warehouse_changes.json
  def create
    p warehouse_change_params
    @warehouse_change = WarehouseChange.new(warehouse_change_params)

    respond_to do |format|
      if @warehouse_change.save
        format.html { redirect_to @warehouse_change, notice: 'Warehouse change was successfully created.' }
        format.json { render :show, status: :created, location: @warehouse_change }
      else
        format.html { render :new }
        format.json { render json: @warehouse_change.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouse_changes/1
  # PATCH/PUT /warehouse_changes/1.json
  def update
    respond_to do |format|
      if @warehouse_change.update(warehouse_change_params)
        format.html { redirect_to @warehouse_change, notice: 'Warehouse change was successfully updated.' }
        format.json { render :show, status: :ok, location: @warehouse_change }
      else
        format.html { render :edit }
        format.json { render json: @warehouse_change.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouse_changes/1
  # DELETE /warehouse_changes/1.json
  def destroy
    @warehouse_change.destroy
    respond_to do |format|
      format.html { redirect_to warehouse_changes_url, notice: 'Warehouse change was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse_change
      @warehouse_change = WarehouseChange.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def warehouse_change_params
      params.require(:warehouse_change).permit(:product_id, :reason_id, :quantity, :description)
    end
end

app/helpers/warehouse_changes_helper.rb
module WarehouseChangesHelper
  def total_warehouse_changed(warehouse_change_list)
    WarehouseChange.get_total_changed(warehouse_change_list)
  end
end

app/views/warehouse_changes/_form.html.erb
<%= form_with(model: warehouse_change, local: true) do |form| %>
  <% if warehouse_change.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warehouse_change.errors.count, "error") %> prohibited this warehouse_change from being saved:</h2>

      <ul>
      <% warehouse_change.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label 'product_id', 'Produto' %>
    <%= form.collection_select(:product_id, products_list, :id, :name, {}, {class: 'custom-select mb-2 mr-sm-2 mb-sm-0'})%>
  </div>

  <div class="form-group">
    <%= form.label :reason_id, 'Motivo' %>
    <%= form.collection_select(:reason_id, reasons_list, :id, :name, {}, {class: 'custom-select mb-2 mr-sm-2 mb-sm-0'})%>
  </div>

  <div class="form-group">
    <%= form.label :quantity, 'Quantidade' %>
    <%= form.number_field :quantity, "aria-describedby" => "quantityHelp" %>
    <small id="quantityHelp" class="form-text text-muted">Quantidade a ser alterada</small>
  </div>

  <div class="actions">
    <%= form.submit 'Criar', class: "btn btn-primary"%>
  </div>
<% end %>

app/views/warehouse_changes/edit.html.erb
<h1>Editing Warehouse Change</h1>

<%= render 'form', warehouse_change: @warehouse_change %>

<%= link_to 'Mostrar', @warehouse_change %> |
<%= link_to 'Voltar', warehouse_changes_path %>

app/views/warehouse_changes/index.html.erb
<h1>Movimentação no Estoque</h1>

<table class="table">
  <thead>
    <tr>
      <th># Change</th>
      <th>Produto</th>
      <th>Quantidade</th>
      <th>Motivo</th>
      <th>DateTime</th>
      <th>Descrição</th>
    </tr>
  </thead>

  <% if @warehouse_changes.length > 0 %>
    <tbody>
      <% @warehouse_changes.each do |warehouse_change| %>
        <tr>
          <th scope="row"><%= warehouse_change.id %></th>
          <td><%= warehouse_change.product.name %></td>
          <td><%= warehouse_change.quantity %></td>
          <td><%= action_name(warehouse_change.reason.action, warehouse_change.reason.name) %></td>
          <td><%= format_datetime(warehouse_change.created_at) %></td>
          <% if warehouse_change.description%>
            <td><%= link_to warehouse_change.description, sale_path(get_sale_id_from_warehouse_change(warehouse_change)), target: '_blank' %></td>
          <%else%>
            <td><%= warehouse_change.description %></td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

<br>

<%= button_to 'Nova Movimentação', new_warehouse_change_path, method: :get, class: 'btn btn-primary' %>

app/views/warehouse_changes/new.html.erb
<h1>Nova Movimentação</h1>

<%= render 'form', warehouse_change: @warehouse_change %>

<%= link_to 'Voltar', warehouse_changes_path %>

app/views/warehouse_changes/show.html.erb
<p>
  <strong>Produto:</strong>
  <%= @warehouse_change.product.name %>
</p>

<p>
  <strong>Motivo:</strong>
  <%= @warehouse_change.reason.name %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @warehouse_change.quantity %>
</p>

<%= link_to 'Editar', edit_warehouse_change_path(@warehouse_change) %> |
<%= link_to 'Voltar', warehouse_changes_path %>