config/routes.rb
Rails.application.routes.draw do
  resources :warehouse_changes
  resources :sale_products

  resources :sales
  post 'sale_disable/:id', to: "sales#disable", as: 'sale_disable'
  get 'start_new_sale', to: "sales#start_new_sale"

  resources :reasons
  root 'welcome#index'
  resources :products

  get 'reports', to: 'reports#index'
  get 'reports_sales', to: 'reports#sales'
  get 'reports_products', to: 'reports#products'
  get 'reports_warehouse_changes', to: 'reports#warehouse_changes'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_products
  accepts_nested_attributes_for :sale_products

  before_save :default_value

  def default_value
    if self.total == ''
      self.total = 0.0
    end
  end

  def get_total_value
    self.sale_products.map{|sp| sp.current_price}.reduce(0, :+)
  end

  def self.remove_invalid_sales
    return true if Sale.all.count == 0
    sale = Sale.all.last
    sale.delete if sale.amount_of_products == 0
  end

  def amount_of_products
    self.sale_products.count
  end

  def disable
    if WarehouseChange.return_itens_to_warehouse(self.id)
      self.active = false
      self.save
      return true
    end
    return false
  end

  def self.actives_sales
    Sale.all.where(active: true)
  end

  def self.filter_by_date(start, finish)
    active_sales = self.actives_sales
    filtered_sales = active_sales.where("created_at >= ? AND created_at <= ?", start.beginning_of_day, finish.end_of_day)
    return filtered_sales
  end

  def self.by_date_and_product(start, finish, product_id)
    filtered_sales = []
    
    Sale.filter_by_date(start, finish).each do |sale|
      if sale.sale_products.where(product_id: product_id).first
        filtered_sales << sale
      end
    end

    return filtered_sales
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy, :disable]
  before_action :remove_invalid_sales, only: [:start_new_sale, :index]

  def index
    @sales = Sale.all
  end

  def show
    
  end

  def new
    @sale = Sale.new
    redirect_to sales_path(@sale)
  end

  def edit
  end

  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # temos dois submit buttons no mesmo form, eh necessario verificar qual foi clicado
    unless params[:add_sale_product]
      redirect_to sales_path
    else
      respond_to do |format|
        if @sale.update(sale_params)
          format.html { redirect_to edit_sale_path(@sale), notice: 'Sale was successfully updated.' }
        else
          format.html { render :edit }
          format.json { render json: @sale.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start_new_sale
    @sale = Sale.create(total: 0.0)
    redirect_to edit_sale_path(@sale)
  end

  def disable
    if @sale.disable
      respond_to do |format|
        format.html { redirect_to sales_url, notice: "Venda cancelada com sucesso. Venda ##{@sale.id}" }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to sales_url, alert: "Algo deu errado com o cancelamento da venda ##{@sale.id}" }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_sale
      @sale = Sale.find(params[:id])
    end

    def sale_params
      params.require(:sale).permit(:total, sale_products_attributes: [:product_id, :quantity, :current_price])
    end

    def remove_invalid_sales
      Sale.remove_invalid_sales
    end
end

app/helpers/sales_helper.rb
module SalesHelper
  def get_all_active_sales
    Sale.actives_sales
  end

  def sale_status(sale)
    ret = ""
    if sale.active
      ret = "<span class='badge badge-info'>Ativo</span>"
    else
      ret = "<span class='badge badge-danger'>Cancelado</span>"
    end
    ret.html_safe
  end
end

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if sale.sale_products.count > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Opções</th>
      </tr>
    </thead>

    <tbody>
      <% sale.sale_products.each_with_index do |sale_product, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= sale_product.product.name %></td>
          <td><%= sale_product.quantity %></td>
          <td>remover</td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <%= form.fields_for :sale_products, @sale.sale_products.build do |sale|%>
        <%= render 'sale_products/sale_product_partial', sale: sale%>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Concluir', class: 'btn btn-success'%>
  </div>
<% end %>

app/views/sales/create.html.erb
<h1>Sales#create</h1>
<p>Find me in app/views/sales/create.html.erb</p>

app/views/sales/destroy.html.erb
<h1>Sales#destroy</h1>
<p>Find me in app/views/sales/destroy.html.erb</p>

app/views/sales/edit.html.erb
<h1>Venda</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Mostrar', @sale %> |
<%= link_to 'Voltar', sales_path %>

app/views/sales/index.html.erb
<h1>Vendas</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="row"># Venda</th>
      <th>Total</th>
      <th>DateTime</th>
      <th>Produtos</th>
      <th colspan="2">Opções</th>
    </tr>
  </thead>

  <tbody>
    <% get_all_active_sales.each do |sale| %>
      <tr>
        <th scope="row"><%= sale.id %></th>
        <td><%= format_money(sale.get_total_value) %></td>
        <td><%= format_datetime(sale.created_at) %></td>
        <td>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Produto</th>
                <th>Quantidade</th>
                <th>Subtotal</th>
              </tr>
            </thead>

            <tbody>
              <% sale.sale_products.each_with_index do |sale_product, index| %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= sale_product.product.name %></td>
                  <td><%= sale_product.quantity %></td>
                  <td><%= format_money(sale_product.current_price) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </td>
        <td><%= link_to 'Mostrar', sale_path(sale) %></td>
        <td><%= link_to sale_disable_path(sale), method: :post, data: {confirm: 'Tem certeza? A venda será cancelada e os produtos voltarão pro estoque'} do%>
          <span class='badge badge-danger'>
            Cancelar
          </span>
          <%end%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= button_to 'Iniciar nova venda', start_new_sale_path, method: :get, class: 'btn btn-primary' %>

app/views/sales/new.html.erb
<%= render 'form', sale: @sale%>

app/views/sales/show.html.erb
<div class="row">
  <div class="col">
    <h1>Venda - ID: <%= @sale.id%></h1>    
  </div>

  <div class="col">
    <h3>Status: <%= sale_status(@sale)%></h3>
  </div>
</div>


<h5><%= format_datetime(@sale.created_at) %></h5>
<br/>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Produto</th>
      <th>Quantidade</th>
      <th>Subtotal</th>
    </tr>
  </thead>

  <tbody>
    <% @sale.sale_products.each_with_index do |sale_product, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= sale_product.product.name %></td>
        <td><%= sale_product.quantity %></td>
        <td><%= format_money(sale_product.current_price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <% if @sale.active%>
    <%= button_to 'Cancelar venda', sale_disable_path(@sale), class: 'btn btn-danger', data: {confirm: 'Tem certeza? A venda será cancelada e os produtos voltarão pro estoque'} %>
  <%end%>

<hr>

<h5>Valor total: <%= format_money(@sale.get_total_value) %></h5>