config/routes.rb
Rails.application.routes.draw do
  resources :warehouse_changes
  resources :sale_products

  resources :sales
  post 'sale_disable/:id', to: "sales#disable", as: 'sale_disable'
  get 'start_new_sale', to: "sales#start_new_sale"

  resources :reasons
  root 'welcome#index'
  resources :products

  get 'reports', to: 'reports#index'
  get 'reports_sales', to: 'reports#sales'
  get 'reports_products', to: 'reports#products'
  get 'reports_warehouse_changes', to: 'reports#warehouse_changes'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def sales
    parameters = reports_params
    @product_searched = Product.find(parameters[:product_id]) if parameters[:product_id]

    if parameters[:start] && parameters[:finish]
      if date_is_valid?(parameters[:start]) && date_is_valid?(parameters[:finish])
        @sales_result = Sale.by_date_and_product(parameters[:start].to_date, 
                                                                                        parameters[:finish].to_date,
                                                                                        parameters[:product_id])
        if @sales_result.count <= 0
          flash.alert = 'Nenhuma venda retornada na data informada.'
        end
      else
        flash.alert = 'Data inválida. Verifique e tente novamente.'
      end
    end
  end

  def products
    @products = Product.all
  end

  # get
  def warehouse_changes
    parameters = reports_params

    if parameters[:start] && parameters[:finish]
      if date_is_valid?(parameters[:start]) && date_is_valid?(parameters[:finish])
        @warehouse_change_result = WarehouseChange.warehouse_changes_by_date_and_product(parameters[:start].to_date, 
                                                                                        parameters[:finish].to_date,
                                                                                        parameters[:product_id])
        if @warehouse_change_result.count <= 0
          flash.alert = 'Nenhum item retornado na data informada.'
        end
      else
        flash.alert = 'Data inválida. Verifique e tente novamente.'
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def reports_params
      return params.permit(:start, :finish, :product_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def get_sale_id_from_warehouse_change(warehouse_change)
    return warehouse_change.description.split('ID: ').last
  end
end

app/views/reports/index.html.erb
<div class="row">
  <div class="col-lg-4 col-md-4">
    <div class="card">
      <div class="card-body padding-card">
        <h5 class="card-title">Produtos</h5>
        <p class="card-text">Informações sobre produtos</p>
        <%= button_to 'Produtos cadastrados', reports_products_path, class: 'btn btn-primary', method: :get, form: {style: 'display:inline-block;'}%>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-4">
    <div class="card">
      <div class="card-body padding-card">
        <h5 class="card-title">Vendas</h5>
        <p class="card-text">Informações Vendas. Podendo fazer pesquisa por produto e data</p>
        <%= button_to 'Vendas', reports_sales_path, class: 'btn btn-info', method: :get, form: {style: 'display:inline-block;'}%>
      </div>
    </div>
  </div>

  <div class="col-lg-4 col-md-4">
    <div class="card">
      <div class="card-body padding-card">
        <h5 class="card-title">Movimentação de estoque</h5>
        <p class="card-text">Informações sobre movimentação de estoque, podendo fazer pesquisa por produto e data</p>
        <%= button_to 'Movimentação de estoque', reports_warehouse_changes_path, class: 'btn btn-warning', method: :get, form: {style: 'display:inline-block;'}%>
      </div>
    </div>
  </div>
</div>

app/views/reports/products.html.erb
<h1>Relatório de produtos</h1>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Imagem</th>
      <th>Total de itens</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each_with_index do |product, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= get_product_image(product) %></td>
        <td><%= total_itens(product.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/sales.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>" role="alert">
    <%= value %>
  </div>
<% end %>
<br/>

<%= form_with(url: reports_sales_path, local: true, method: :get) do |form| %>
  <div class="form-row">

    <div class="col-md-4 mb-3">
      <%= form.label 'product_id', 'Produto' %>
      <%= form.collection_select(:product_id, products_list, :id, :name, {}, {class: 'custom-select mb-2 mr-sm-2 mb-sm-0'})%>
    </div>

    <div class="col-md-4 mb-3">
      <%= form.label :start, 'Início' %>
      <%= form.text_field :start, "aria-describedby" => "startHelp", class: 'input-date-mask', value: "#{DateTime.now.beginning_of_year.strftime('%d/%m/%Y')}"%>
      <small id="startHelp" class="form-text text-muted">Data Início</small>
    </div>

    <div class="col-md-4 mb-3">
      <%= form.label :finish, 'Fim' %>
      <%= form.text_field :finish, "aria-describedby" => "finishHelp", class: 'input-date-mask', value: "#{DateTime.now.end_of_year.strftime('%d/%m/%Y')}"%>
      <small id="finishHelp" class="form-text text-muted">Data Fim</small>
    </div>

    <div class="actions col-md-4 mb-3">
      <%= form.submit 'Filtrar', class: "btn btn-primary"%>
    </div>
  </div>
<%end%>

<br/>
<hr>
<%= "Item procurado: #{@product_searched.name}" if @product_searched%>
<% if @sales_result %>
  <table class="table">
    <thead>
      <tr>
        <th scope="row"># Venda</th>
        <th>Total</th>
        <th>DateTime</th>
        <th>Produtos</th>
      </tr>
    </thead>

    <tbody>
      <% @sales_result.each do |sale| %>
        <tr>
          <th scope="row"><%= sale.id %></th>
          <td><%= format_money(sale.get_total_value) %></td>
          <td><%= format_datetime(sale.created_at) %></td>
          <td>
            <table>
              <thead>
                <tr>
                  <th>#</th>
                  <th>Produto</th>
                  <th>Quantidade</th>
                  <th>Subtotal</th>
                </tr>
              </thead>

              <tbody>
                <% sale.sale_products.each_with_index do |sale_product, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <% if @product_searched.id == sale_product.product.id%>
                      <td><span class='badge badge-success'><%= sale_product.product.name %></span></td>
                    <%else%>
                      <td><%= sale_product.product.name %></td>
                    <%end%>
                    <td><%= sale_product.quantity %></td>
                    <td><%= format_money(sale_product.current_price) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/reports/warehouse_changes.html.erb
<br/>

<%= form_with(url: reports_warehouse_changes_path, local: true, method: :get) do |form| %>
  <div class="form-row">

    <div class="col-md-4 mb-3">
      <%= form.label 'product_id', 'Produto' %>
      <%= form.collection_select(:product_id, products_list, :id, :name, {}, {class: 'custom-select mb-2 mr-sm-2 mb-sm-0'})%>
    </div>

    <div class="col-md-4 mb-3">
      <%= form.label :start, 'Início' %>
      <%= form.text_field :start, "aria-describedby" => "startHelp", class: 'input-date-mask', value: "#{DateTime.now.beginning_of_year.strftime('%d/%m/%Y')}"%>
      <small id="startHelp" class="form-text text-muted">Data Início</small>
    </div>

    <div class="col-md-4 mb-3">
      <%= form.label :finish, 'Fim' %>
      <%= form.text_field :finish, "aria-describedby" => "finishHelp", class: 'input-date-mask', value: "#{DateTime.now.end_of_year.strftime('%d/%m/%Y')}"%>
      <small id="finishHelp" class="form-text text-muted">Data Fim</small>
    </div>

    <div class="actions col-md-4 mb-3">
      <%= form.submit 'Filtrar', class: "btn btn-primary"%>
    </div>
  </div>
<%end%>

<br/>
<hr>
<br/>

<% if @warehouse_change_result %>
  <table class="table">
    <thead>
      <tr>
        <th># Change</th>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Motivo</th>
        <th>DateTime</th>
        <th>Descrição</th>
      </tr>
    </thead>

    <tbody>
      <% @warehouse_change_result.each do |warehouse_change| %>
        <tr>
          <th scope="row"><%= warehouse_change.id %></th>
          <td><%= warehouse_change.product.name %></td>
          <td><%= warehouse_change.quantity %></td>
          <td><%= action_name(warehouse_change.reason.action, warehouse_change.reason.name) %></td>
          <td><%= format_datetime(warehouse_change.created_at) %></td>
          <% if warehouse_change.description%>
            <td><%= link_to warehouse_change.description, sale_path(get_sale_id_from_warehouse_change(warehouse_change)), target: '_blank' %></td>
          <%else%>
            <td><%= warehouse_change.description %></td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2><%= "Total movimentado: #{total_warehouse_changed(@warehouse_change_result)}"%></h2>
<%end%>