config/routes.rb
Rails.application.routes.draw do
  resources :warehouse_changes
  resources :sale_products

  resources :sales
  post 'sale_disable/:id', to: "sales#disable", as: 'sale_disable'
  get 'start_new_sale', to: "sales#start_new_sale"

  resources :reasons
  root 'welcome#index'
  resources :products

  get 'reports', to: 'reports#index'
  get 'reports_sales', to: 'reports#sales'
  get 'reports_products', to: 'reports#products'
  get 'reports_warehouse_changes', to: 'reports#warehouse_changes'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Navbar</a> -->
      <%= link_to 'Stock', root_path, class: "navbar-brand"%>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= current_page?(products_path) ? 'active' : '' %>">
            <%= link_to 'Produtos cadastrados', products_path, class: "nav-link"%>
          </li>
          <li class="nav-item <%= current_page?(sales_path) ? 'active' : '' %>">
            <%= link_to 'Vendas', sales_path, class: "nav-link"%>
          </li>

          <li class="nav-item <%= current_page?(reasons_path) ? 'active' : '' %>">
            <%= link_to 'Motivos', reasons_path, class: "nav-link"%>
          </li>
          <li class="nav-item <%= current_page?(warehouse_changes_path) ? 'active' : '' %>">
            <%= link_to 'Movimentação Estoque', warehouse_changes_path, class: "nav-link"%>
          </li>

          <li class="nav-item <%= current_page?(reports_path) ? 'active' : '' %>">
            <%= link_to 'Relatórios', reports_path, class: "nav-link" %>
          </li>
        </ul>

      </div>
    </nav>


    <div class="container-fluid">
      <div class="container-padding">
        <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %>" role="alert">
            <%= value %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>


  </body>
</html>